spring:
  rabbitmq:
    host: 192.168.59.130
    username: woldier
    password: woldier
    virtual-host: /woldier
    port: 5672
    #-----publisherConfirms增强
#    publisherConfirms: true
    #-----publisherConfirms增强
#    publisherReturns: true
    #开启ack 为手动
    listener:
      simple:
        acknowledge-mode: manual